[window]
decorations = "None"
padding = { x = 4, y = 4 }
opacity = 0.95
blur = true

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }

[cursor]
style = { blinking="Always" }

